### ISSUE TITLE
Decouple URLs from AWS so Minio can be used as alternative. 

### ISSUE THREAD

**Issue by c4milo** [craftcms/aws-s3#10]
I've been trying to use Minio with CraftCMS, but I keep getting the following error despite having configured Minio URL as `url` in the volume's configuration. 

![](https://cldup.com/hfVS-zUaO1.png) 

Here is my volume's configuration for my local Minio instance (Credentials are temporary and local 😛 ): 

![](https://cldup.com/Rfrs_ylw5l.png)

**Comment by andris-sevcenko** [comment]
@c4milo If you try this with an actual S3 bucket, does this issue go away, indicating that this is a problem with Minio?

The error would suggest that your system time might be to blame - is your system time correct and is your timezone set correctly?

**Comment by c4milo** [comment]
@andris-sevcenko it works with AWS S3, yes. It does not work with Minio. The original error was related to my VM's clock being skewed. I'm now getting and error about token ID being invalid, when using Minio.

**Comment by andris-sevcenko** [comment]
Can you share the full error message?

**Comment by c4milo** [comment]
@andris-sevcenko 

![](https://cldup.com/eBW0cis4yc.png)

**Comment by andris-sevcenko** [comment]
AWS-S3 plugin uses [temporary security credentials](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html) to sign all requests to AWS. The main reason for doing so is so that the tokens can be cached, instead of being re-requested for each request.

In this case, it seems the plugin is requesting AWS STS for a session token with invalid credentials, which makes sense, since the credentials are for your Minio instance.

So, I'd say this plugin is incompatible with Minio, because it uses more than just S3 to render the services.

The good news is, though, that there's nothing stopping you from forking this plugin to remove the [token caching](https://github.com/craftcms/aws-s3/commit/335d0184b3aa93516060881aeae2ad42a62c76a2) which should make it work with Minio.
