### ISSUE TITLE
Possible to store metadata in the S3 object?

### ISSUE THREAD

**Issue by terbolous** [craftcms/aws-s3#11]
When reindexing it takes a long time and most of the time seems to be due to Craft downloading all assets to get their size (both file size and image size).

File size should be directly accessible from S3 as is, but image size could be stored as a custom metadata and efficiently (hopefully) remove the need to download files just to reindex them.

**Comment by andris-sevcenko** [comment]
Asset indexing most often is used to get Assets inside Craft that have been there previously, therefore they would not have this metadata, anyway and it's possible to add metadata only when copying or uploading a file to AWS S3, rendering this approach feasible in just a tiny amount of cases.

We've toyed with approaches like this but ultimately settled with the lightbox switch "cache remote images". If left off, Craft will download only as little of the file as it needs to determine the image dimensions from the file contents. It is rarely more than a few kilobytes.

The long indexing time you observe is because of the SSL handshake for each connection (so, at least N+1 connections where N is file count) which cannot be avoided...
