### ISSUE TITLE
retain original filename for asset without mtime param in url

### ISSUE THREAD

**Issue by bkmorse** [craftcms/aws-s3#117]
### Description
I built a plugin that retains the original filename. If a user replaces an existing asset, it retains the original filename and sets that as the filename for the file that it was replaced by. I use EVENT_BEFORE_REPLACE_ASSET and EVENT_AFTER_REPLACE_ASSET to accomplish this.

Then we installed craftcms/aws-s3 and configured it to use S3.

The filename is retained but it includes a mtime param in the url, which is different each time the file is replaced.

This might not be a bug but wondering if there is a way to retain the same mtime or getting rid of it from the url altogether.

The purpose of the plugin to retain the same filename because they would updating assets and people would be bookmarking the assets and they do not want any deadlinks.

### Additional info

- Craft 3.5.17.1
- PHP version: 7.3.2
- "craftcms/aws-s3": "1.2.11"

**Comment by andris-sevcenko** [comment]
The `mtime` parameter is there only if you have configured the `expires` setting for the volume and it is used to bust cache.

Otherwise, if a user downloads the asset and caches it for, for example, 30 days and you modify the asset, the browser will simply return it from the cache and not get the new version, which seems to be the opposite of what you want.

You can use the `craft/services/Assets::EVENT_GET_ASSET_URL` event to return whatever URL you wish, though, if you want to override this behavior and don't wish to remove the `expires` setting.
