### ISSUE TITLE
Path to Sub-Subfolder Not Working

### ISSUE THREAD

**Issue by andrea-hall** [craftcms/aws-s3#21]
I have an S3 bucket set up with a folder structure like this:

root
— craft-assets
— — blog

I'm able to set up a volume using "craft-assets" as the "path to subfolder," and when I'm viewing that volume I get "blog" as a subfolder under a dropdown. However, I'd like to connect directly to the blog folder. I tried creating a similar volume with "craft-assets/blog" as the path to subfolder, but I always get a 403 Forbidden error when I try to upload to it. 

Can the path to subfolder only be one folder deep?

**Comment by andris-sevcenko** [comment]
Subfolders can be as deep as needed. I'm unable to reproduce this locally, so not sure what's going wrong for you.

How is the HTTP 403 error presented to you? Is there something tangible in your browser's javascript console or your Craft logs?

**Comment by andrea-hall** [comment]
Ah! I figured it out as I was taking screenshots to send to you. My original volume had "Assets in this volume have public URLs" turned off, but my blog volume had it on. Turning it off fixed the issue.

If I were to have that on, though, would I need to include the path to the subfolder in "Base Url"? 

For reference, I had been getting a modal on upload with the following error:

```
Upload failed. The error message was: "Error executing "PutObject" on "{volume location}/image.jpg"; AWS HTTP error: Client error: 'PUT {volume location}/image.jpg' resulted in a '403 Forbidden' response: 
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>XXXXX (truncated...) AccesDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>XXXXXXXXXXXXXXXXXXXXX</RequestId><HostId>XXXXXXXXXXXXXXXXXX=</HostId</Error>
```

**Comment by andrea-hall** [comment]
I'm running into this issue again. I can't get away with turning public URLs off, and I can't avoid this error message when it's on.

I'm testing a volume that connects to my bucket's root folder. I can connect to the bucket through S3, and I can save images to it through Craft if public URLs are off. So I must be formatting the base url wrong somehow.

I uploaded a test image to the bucket and it's accessible at https://s3.amazonaws.com/assets.schellgames.com/test.png

So I set my volume's base URL to "//s3.amazonaws.com/assets.schellgames.com", but this resulted in the 403 Forbidden error when I try to upload anything. 

I also tried "assets.schellgames.com" and "//s3.amazonaws.com" and all those versions with the https: on front. All are throwing the error. No matter what I put in there, the error references the correct url: "Error executing PutObject on "https://s3.amazonaws.com/assets.schellgames.com/test.png"..."

What am I missing here?

**Comment by andris-sevcenko** [comment]
Uploading has nothing to do with the base URL - that's just used to access uploaded Assets.

Is it possible to get CP access? If you, can you get in touch via support@craftcms.com?

**Comment by harnasz** [comment]
Hi @andris-sevcenko I have experienced the same issue as @andrea-hall. 

To sum it up, if you have the `Assets in this volume have public URLs` toggled to true and point the `Base URL` to your S3 bucket then it will fail to upload. If you have it toggled off then the upload will succeed. 

Craft CMS's Volumes `\craft\base\FlysystemVolume` extend the Leagues Flystem.

When trying to upload the file with public URL's turned ON `\craft\base\FlysystemVolume::createFileByStream` is invoked which then invokes `\craft\base\FlysystemVolume::addFileMetadataToConfig` to add extra file meta data to the config which is then passed into the Flysystems method `\League\Flysystem\Filesystem::writeStream`

`addFileMetadataToConfig` extends the config by adding a `visibility` element to the array which is interpreted by Flysystem (read more here http://flysystem.thephpleague.com/docs/usage/filesystem-api/#manage-visibility).

When the S3 Flysystem makes the put request to S3 it tries to set the file to be publicly readable and for this you need the `s3:PutObjectAcl` permission. 

I'm using the volume to serve static files by turning on static website hosting feature to make everything public then placing Cloudflare in-front of the bucket to act as the CDN and because of this I don't need this public read permission. 

My recommendation would be to place an example S3 Bucket Policy in the README and how to use the S3 volumes feature within Craft in a variety of common implementations, such as Cloudflare or CloudFront.

So my S3 config looks something like this:

```
{
    "Effect": "Allow",
    "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:DeleteObject",
        "s3:PutObjectAcl"
    ],
    "Resource": [
        "arn:aws:s3:::bucket/*"
    ]
}
```

**Comment by andris-sevcenko** [comment]
> I'm using the volume to serve static files by turning on static website hosting feature to make everything public then placing Cloudflare in-front of the bucket to act as the CDN and because of this I don't need this public read permission.

Any particular reason why you'd choose to involve Craft in that? I mean, if you don't plan to serve the Assets through Craft, then why have the Public URL setting enabled?

**Comment by harnasz** [comment]
In our instance we are using CraftCommerce, we are uploading images to our products which we offload onto S3. 

We use the public URL option so when we do the following:

`<img class="featured-image-hover-js is-active" src="{{ asset.url }}" alt="{{ category.title }}" />a`

The system outputs the full URL. Are we doing this wrong?

**Comment by andris-sevcenko** [comment]
@harnasz no, it's all correct. I was just confused about your phrasing there.

So, for an S3 object to be accessible from the outside, either it explicitly has to be enabled for reading by everyone, or else the bucket needs to have a policy that explicitly sets everything in the bucket to be readable. Either way, if the Volume is supposed to have an URL, the uploaded files should be readable.

Realistically, it's more likely that a given policy has rights to modify ACL, than that the bucket has the policy set.

I agree, though, that a general policy might be useful in the README, though.

**Comment by harnasz** [comment]
Thanks @andris-sevcenko, you explained that much better than me!

**Comment by shaneboy** [comment]
@harnasz thank you for this! resolved many hours of frustrating trouble-shooting!

**Comment by andris-sevcenko** [comment]
Added the policy to the readme.
