### ISSUE TITLE
Update 'Bucket' setting to allow plain text input of bucket name instead of requiring ListAllMyBuckets permission

### ISSUE THREAD

**Issue by BenParizek** [craftcms/aws-s3#24]
If you already know the bucket name, there is no need to add the ListAllMyBuckets setting to your IAM User permissions. This method is just a convenience for the UI.

It would be nice to have a plain text option to specify the bucket name if it's already known so bucket permissions can be more restrictive. In agency situations, the ListAllMyBuckets permission exposes all other bucket names which an agency may not want a client to see.

**Comment by andris-sevcenko** [comment]
Craft won't list any buckets it cannot fetch the location for, so [shamelessly plugging my SE answer here](https://craftcms.stackexchange.com/a/13870/258).

Also, this should be solved eventually with craftcms/cms#1429

**Comment by ldennison-bsd** [comment]
I believe there is a fundamental misunderstanding here. Ben is requesting that Craft not **require** the s3:ListAllMyBuckets IAM permission, but instead make it optional. We do not care about the s3:GetBucketLocation IAM permission. The reason for this is because of how these two permissions work fundamentally. The s3:ListAllMyBuckets permission cannot be limited to apply to only certain buckets. So, if an IAM user has the s3:ListAllMyBuckets permission, then they are able to see literally **all** S3 buckets in the associated AWS account. It's all or nothing; they can either list all the bucket names (i.e. s3:ListAllMyBuckets permission), or they can't list any (i.e. don't have s3:ListAllMyBuckets permission).

The s3:GetBucketLocation permission can be limited to apply to only certain buckets, just as all of the other s3 object permissions (PutObject, DeleteObject, etc.). Thus, via proper IAM policy, we can "lock down" all s3 permissions to a single bucket, **except** the listing of all bucket names.

Craft requires the s3:ListAllMyBuckets permission solely to populate the list of bucket names in the Bucket Name dropdown. The bucket names are retrieved once, shown in the dropdown for the user to select a specific value, and then stored as a string in the Volume settings so it can be used on future API calls to S3. The current UI implementation is just a convenience feature that necessitates the s3:ListAllMyBuckets permission by nature of how it works. If an alternative UI option was implemented during Volume creation to allow the user to simply enter the bucket name string without using the dropdown, then we bypass the need for the s3:ListAllMyBuckets permission altogether. That's what Ben is asking.

Off the top of my head, perhaps you add a checkbox under the current Bucket Name dropdown like "Specify bucket name instead" and checking that shows a plain-text field that's used instead for "Bucket Name" of the dropdown value.

Regardless of how the UI is executed, the feature request is fairly simple and highly necessary for us agencies that maintain strict security policy in AWS for compliance and just downright good practice.

**Comment by andris-sevcenko** [comment]
@ldennison-bsd I see where you're coming from with this.

Craft 3.1 will probably alleviate this in one way or another, but this plugin could benefit from this feature.

Having said that, there's little chance we'll be able to get to that before 3.1 hits beta simply due to our bandwidth, so, if waiting a bit for that does not sound like a good option, we always welcome pull requests as means of lending a helping hand.

**Comment by ldennison-bsd** [comment]
@andris-sevcenko We might be able to submit something. While the work is fairly trivial, I imagine we might differ in UI approach. Do you all have a preference for how the UI element would be implemented (e.g. checkbox, extra button, etc.)?

**Comment by andris-sevcenko** [comment]
The checkbox + input would be good enough.

Please keep in mind, though, that you'd have to specify region then as well, which is something Craft does for you when you select a bucket from the list.

**Comment by andris-sevcenko** [comment]
This has been implemented with 69a14bd787a9ed3c3f4de82bed336ee48bb81b1d
