### ISSUE TITLE
CSS files cannot be uploaded

### ISSUE THREAD

**Issue by webtrend** [craftcms/aws-s3#30]
When I try to upload a CSS using craft webUI using Amazon S3 plugin, I get an error that file type not allowed

If I use a third party tool to upload a css file on my S3 bucket, craft refuses to index that file (manual indexing)

Why? This was never an issue on Craft 2

BTW, this might be an issue with other types of files too (like js). I have not checked yet.

**Comment by andris-sevcenko** [comment]
You can configure the allowed file extensions using the [allowedFileExtensions](https://docs.craftcms.com/v3/config/config-settings.html#allowedfileextensions) and [extraAllowedFileExtensions](https://docs.craftcms.com/v3/config/config-settings.html#allowedfileextensions).

If you want to add extensions to the list, it is recommended to use the latter setting, as using the first one will overwrite the allowed extensions. Also, this behavior has not changed since Craft 2, so maybe you were just working on an install with the config setting already set.
