### ISSUE TITLE
Upload gets stuck at 100%

### ISSUE THREAD

**Issue by webtrend** [craftcms/aws-s3#66]
When I try to upload a file by clicking on Assets in sidebar and then Upload an image to a specific bucket, it gets stuck at 100% progress bar. **This only happens with a few images not all and it seems like it mostly happens with extremely small images ~2KB**

We have a staging server with same configuration and the problem is non-existent on staging server which suggests that the problem is on our production server. How do we go about troubleshooting this problem?

**Comment by andris-sevcenko** [comment]
Sounds like there's an error when processing the uploaded image. There probably should be something in your log folders. Can you take a look? Another option is taking a look at the response body for the ajax request that uploads the image. If the upload bar gets stuck, there's a great chance that it's because the response from the server is not a JSON response but is, instead, a PHP error stack trace.

**Comment by andris-sevcenko** [comment]
Closing due to lack of response.
