### ISSUE TITLE
FR: Add security token for temporary security credentials 

### ISSUE THREAD

**Issue by lukebailey** [craftcms/aws-s3#80]
For local development purposes, access key/secret to an S3 bucket is becoming discouraged in place of temporary credentials as outlined in the following link from AWS: 

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

The main difference is an additional security token which I can see is already supported by the underlying S3 client used by this plugin. 

Could we include an additional (optional) environment variable to support this scenario?

**Comment by andris-sevcenko** [comment]
This plugin already uses STS tokens [under the hood](https://github.com/craftcms/aws-s3/blob/master/src/Volume.php#L409-L430) as outlined in the documentation you linked.

If I'm reading [this table](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#stsapi_comparison) right, then you either have to use a 3rd party service token or IAM credentials to get the token, so, at some point, the credentials still have to be stored somewhere and be accessible to generate a new token, once it expires, since the maximum duration of an STS token is 36 hours.
