### ISSUE TITLE
Error executing "GetSessionToken"

### ISSUE THREAD

**Issue by michaelfromtheoutfit** [craftcms/aws-s3#81]
Hey folks!

I'm currently trying to upgrade a Craft 2 site to Craft 3.4.4.1. However I'm getting the following error whenever I try to access any image transforms from my templates.

`
Aws\Sts\Exception\StsException
Error executing "GetSessionToken" on "https://sts.us.amazonaws.com"; AWS HTTP error: cURL error 6: Could not resolve host: sts.us.amazonaws.com
`

If I go to Settings->Assets I can see all my Amazon S3 volumes.
If I go to Assets I can see all of my images, but none of the thumbnails are working.

Thanks so much for any help!

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue is actually the same as #81. Can you open the Volume settings, click "Refresh" next to the bucket, select a different bucket, then select the original bucket and then click save? That should fix up your region settings in the database which is causing the incorrect hostname error.

Let me know if that helps!

**Comment by michaelfromtheoutfit** [comment]
That worked great! Thank you so much - I really appreciate the help!

**Comment by olets** [comment]
>  This issue is actually the same as #81.

@andris-sevcenko do you remember which issue you had in mind? (This _is_ 81) I'm running into something that might be similar and am hoping to read any additional conversations. Not finding an obvious contender in search

**Comment by andris-sevcenko** [comment]
@olets my apologies. I definitely meant https://github.com/craftcms/aws-s3/issues/36 that time. Sorry for the confusion!
